# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b05ab6dcf45fe1ee61552a4817378307f8d91527111646f3e8ae54274328ecd39512f33c055f4da775e165c61f89c6065350a6fe4646bfaf3b70151612c869c8

test:
  secret_key_base: 7b5c3e4c554853482b8ad2c8165b94f69bec20ac791f34f3142c50f6b36c8b441c30c6abbc75ab52faf1346d0631cb8df4ad0a5ee0311fba3c4823d5f31016f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
